### ISSUE TITLE
Use `serde` instead of deprecated `rustc-serialize`

### ISSUE THREAD

**Issue by tailhook** [tailhook/rust-quire#9]

**Comment by dtolnay** [comment]
It is now officially deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

**Comment by tailhook** [comment]
Yes. But probably we will not use serde here, but provide our own "derive" implementation. This is faily big amount of work though.

**Comment by tailhook** [comment]
Okay, we're now using serde in master. Will release soon after some testing in dependent projects.
